# Generated by Django 3.0.7 on 2021-02-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("email_tool", "0023_auto_20210216_1635"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="A short description of the file.", max_length=512),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Select a document upload.",
                        unique=True,
                        upload_to="documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The customer this document is associated with if there is one.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="email_tool.Customer",
                        verbose_name="Associated with Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
