# Generated by Django 3.0.7 on 2021-02-18 00:01

import django.core.validators
from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="document",
        ),
        migrations.AddField(
            model_name="document",
            name="resource",
            field=models.FileField(
                default=" ",
                help_text="Accepted file types: docx, doc, pdf, xls and xlsx.\n Max file size: 25 MB.",
                upload_to="documents",
                validators=[
                    document.models.Document.validate_max_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx", "doc", "pdf", "xls", "xlsx"]
                    ),
                ],
                verbose_name="Document",
            ),
        ),
    ]
