# Generated by Django 3.0.7 on 2021-02-18 06:34

import django.core.validators
from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_auto_20210217_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="resource",
            field=models.FileField(
                help_text="Accepted file types: doc,docx,pdf,xlsx,xls,png,jpg,csv,pptx,pbix.\n Max file size: 25 MB.",
                upload_to="documents/",
                validators=[
                    document.models.Document.validate_max_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "pdf",
                            "xlsx",
                            "xls",
                            "png",
                            "jpg",
                            "csv",
                            "pptx",
                            "pbix",
                        ]
                    ),
                ],
                verbose_name="Document",
            ),
        ),
    ]
