# Generated by Django 3.0.7 on 2020-07-19 21:13

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 7, 19, 21, 13, 0, 58914),
                help_text="Set the follow up date that you have confirmed with the Candidate.",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Add any notes about this Candidate.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="tech_stack",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("SQL", "SQL"),
                    ("Java", "Java"),
                    ("Python", "Python"),
                    ("Microsoft PowerBI", "Microsoft PowerBI"),
                    ("MSSQL", "MSSQL"),
                    ("HTML", "HTML"),
                    ("CSS", "CSS"),
                    ("AWS", "AWS"),
                    ("Crystal Reports", "Crystal Reports"),
                    (".NET", ".NET"),
                    ("C#", "C#"),
                ],
                help_text="Check the technologies the Candidate has experience with.",
                max_length=76,
            ),
        ),
    ]
