# Generated by Django 3.0.7 on 2020-07-19 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_auto_20200719_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="cv",
            field=models.FileField(blank=True, default="test.pdf", null=True, upload_to="candidate_resumes"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 7, 19, 21, 48, 16, 674845),
                help_text="Set the follow up date that you have confirmed with the Candidate.",
            ),
        ),
    ]
