# Generated by Django 3.0.7 on 2020-07-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_auto_20200719_2148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="follow_up_date",
        ),
    ]
