# Generated by Django 3.0.7 on 2021-02-15 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("candidates", "0005_auto_20210213_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The Candidate's primary contact at Fidelis.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
