# Generated by Django 3.0.7 on 2021-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_candidate_primary_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="it_skills",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONE", "1"),
                    ("TWO", "2"),
                    ("THREE", "3"),
                    ("FOUR", "4"),
                    ("FIVE", "5"),
                ],
                default="THREE",
                help_text="Rate the Candidates IT skills.",
                max_length=256,
                null=True,
                verbose_name="IT skills",
            ),
        ),
    ]
