# Generated by Django 3.0.7 on 2021-02-26 03:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_auto_20210215_0117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=50, null=True
            ),
        ),
    ]
