"""
Django settings for bulk_email project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

# This configures the repo root to be the base path.
BASE_DIR = os.path.dirname(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../.."))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")


ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".herokuapp.com"]


# Application definition

DJANGO_APPS = (
    "django.contrib.humanize",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
)

THIRD_PARTY_APPS = (
    "import_export",
    "mail_templated",
    "phone_field",
    "ckeditor",
    "multiselectfield",
    "storages",
    "letsencrypt",
    "auditlog",
    "gsheets",
    "crispy_forms",
)

# Apps specific for this project go here.
LOCAL_APPS = (
    "email_tool.apps.EmailToolConfig",
    "candidates.apps.CandidatesConfig",
    "document.apps.DocumentConfig",
)

# See: https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "bulk_email.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bulk_email.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Email Configs #

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = config('GMAIL_USER', '')
# EMAIL_HOST_PASSWORD = config('GMAIL_PASSWORD', '')
# EMAIL_USE_TLS = True

# Email Configs #

EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = config("EMAIL_USER", "")
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD", "")
EMAIL_USE_TLS = True


# Ckeditor Configs #
CKEDITOR_CONFIGS = {
    "default": {
        "skin": "moono",
        "toolbar": "basic",
        "enterMode": 2,
    },
}

# Django-Jazzmin Admin Theme Configs #
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Welcome to Django Admin CRM",
    # Title on the brand, and login screen (19 chars max)
    # (defaults to current_admin_site.site_header if absent or None)
    "site_header": "",
    # square logo to use for your site, must be present in static files, used for favicon and brand on top left
    "site_logo": "fidelis-logo_DdDHVdk.png",
    # Welcome text on the login screen
    "welcome_sign": "An easy-to-use and powerful CRM for your business.",
    # Copyright on the footer
    "copyright": "Brook Rodia and Mike Varga",
    # The model admin to search from the search bar, search bar omitted if excluded
    # "search_model": "auth.User",
    # Field name on user model that contains avatar image
    "user_avatar": "auth.User",
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "email_tool"},
        {"app": "candidates"},
        {"app": "document"},
        # external url that opens in a new window (Permissions can be added)
        {
            "name": "Our Company Site",
            "url": "https://fidelis-partners.com",
            "new_window": True,
        },
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],
    #############
    # User Menu #
    #############
    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {
            "name": "Our Company Site",
            "url": "https://fidelis-partners.com",
            "new_window": True,
            "icon": "fas fa-globe",
        },
        {"model": "auth.user"},
    ],
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # # Hide these apps when generating side menu e.g (auth)
    # "hide_apps": [],
    # # Hide these models when generating side menu (e.g auth.user)
    # "hide_models": [],
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        "email_tool",
        "candidates",
        "document",
        "auditlog",
        # "letsencrypt",
        "auth",
    ],
    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "document": [
            {
                "name": "Customer Summary Report",
                "url": "https://app.powerbi.com/view?r=eyJrIjoiMDVkOTE1NmEtMjZjYi00ODA4LWJkYzUtMDZhNGU3OWZhM2QxIiwidCI6Ijc2NjExYTdlLTFlNDMtNDI0OS1iMGY2LWExOWFjMjJlZDg4YyJ9&pageName=ReportSection539610db04667f8476e9",
                "new_window": True,
                "icon": "fas fa-chart-pie",
            },
            {
                "name": "Action Item Summary Report",
                "url": "https://app.powerbi.com/view?r=eyJrIjoiMDVkOTE1NmEtMjZjYi00ODA4LWJkYzUtMDZhNGU3OWZhM2QxIiwidCI6Ijc2NjExYTdlLTFlNDMtNDI0OS1iMGY2LWExOWFjMjJlZDg4YyJ9&pageName=ReportSection",
                "new_window": True,
                "icon": "fas fa-chart-bar",
            },
            {
                "name": "Action Item Calendar Report",
                "url": "https://app.powerbi.com/view?r=eyJrIjoiMDVkOTE1NmEtMjZjYi00ODA4LWJkYzUtMDZhNGU3OWZhM2QxIiwidCI6Ijc2NjExYTdlLTFlNDMtNDI0OS1iMGY2LWExOWFjMjJlZDg4YyJ9&pageName=ReportSection1f9ca3d1a10521ac2746",
                "new_window": True,
                "icon": "fas fa-chart-bar",
            },
            {
                "name": "Email Summary Report",
                "url": "https://app.powerbi.com/view?r=eyJrIjoiMDVkOTE1NmEtMjZjYi00ODA4LWJkYzUtMDZhNGU3OWZhM2QxIiwidCI6Ijc2NjExYTdlLTFlNDMtNDI0OS1iMGY2LWExOWFjMjJlZDg4YyJ9&pageName=ReportSectione0315188a835650104e0",
                "new_window": True,
                "icon": "fas fa-chart-pie",
            },
        ],
    },
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free
    # for a list of icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-user-friends",
        "email_tool.customer": "fas fa-users",
        "email_tool.emailbatch": "fas fa-mail-bulk",
        "email_tool.emailmessage": "fas fa-envelope",
        "email_tool.imageresource": "fas fa-images",
        "email_tool.nextactionitem": "fas fa-calendar-alt",
        "candidates.candidate": "fas fa-briefcase",
        "candidates.techstack": "fas fa-laptop-code",
        "document.document": "fas fa-file-upload",
        "auditlog.logentry": "fas fa-file-alt",
        "letsencrypt.acmechallenge": "fas fa-key",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": True,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "jazzmin_ui_tweaks.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}

# This is the path CKEDITOR will look for media files when uploading via Admin Panel text editor.
CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR, "media")
# TO DO - Create a media directory and add it here ^

# Django Admin Theme Configuration
X_FRAME_OPTIONS = "SAMEORIGIN"

LOGIN_URL = "/login/"

## Static file Settings ##
##########################
# (CSS, JavaScript, Images)
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# Media #
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Google Sheets Document ID's
GSHEETS_CUSTOMER_SHEET_ID = config("GSHEETS_CUSTOMER_SHEET_ID", None)

# Google Sheets Api Integration
GSHEETS = {"CLIENT_SECRETS": "google-credentials.json"}

# Crispy Forms
CRISPY_TEMPLATE_PACK = "bootstrap4"
