# Generated by Django 3.0.7 on 2020-06-14 00:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=200, null=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
                ),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAD_NUMBER", "Bad Number"),
                            ("VOICEMAIL", "Voicemail"),
                            ("SETUP_CALLBACK", "Setup Callback"),
                            ("WARM", "Warm"),
                            ("HOT", "Hot"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "send_succeeded",
                    models.BooleanField(
                        help_text="Indicates that an email has been sent and whether it succeeded or failed."
                    ),
                ),
                ("unsubscribed", models.BooleanField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_tool.Customer",
                    ),
                ),
            ],
        ),
    ]
