# Generated by Django 3.0.7 on 2020-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
