# Generated by Django 3.0.7 on 2020-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0002_auto_20200614_2346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("BAD_NUMBER", "Bad Number"),
                    ("VOICEMAIL", "Voicemail"),
                    ("SETUP_CALLBACK", "Setup Callback"),
                    ("WARM", "Warm"),
                    ("HOT", "Hot"),
                ],
                default="NOT_SET",
                max_length=256,
                null=True,
            ),
        ),
    ]
