# Generated by Django 3.0.7 on 2020-06-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0003_auto_20200615_0140"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="template_file",
            field=models.CharField(choices=[("test.tpl", "TEST")], default="test.tpl", max_length=256),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="send_succeeded",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates that an email has been sent and whether it succeeded or failed.",
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="unsubscribed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
