# Generated by Django 3.0.7 on 2020-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0004_auto_20200617_0309"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OTHER", "Other"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("HEALTHCARE", "Healthcare"),
                    ("FINANCE", "Finance"),
                ],
                default="MANUFACTURING",
                max_length=256,
                null=True,
            ),
        ),
    ]
