# Generated by Django 3.0.7 on 2020-06-17 22:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0005_customer_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="custom_message",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
