# Generated by Django 3.0.7 on 2020-07-08 00:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0006_auto_20200617_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="customer_quote",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="subject",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="title",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="template_file",
            field=models.CharField(choices=[("test.html", "TEST")], default="test.html", max_length=256),
        ),
    ]
