# Generated by Django 3.0.7 on 2020-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0007_auto_20200708_0049"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                default="fidelis_logo.png",
                help_text="Choose a Company Logo",
                upload_to="email_images",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="customer_image",
            field=models.ImageField(
                blank=True,
                default="tube-one.jpg",
                help_text="Choose a Customer Image",
                upload_to="email_images",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="customer_logo",
            field=models.ImageField(
                blank=True,
                default="tube-one-logo.jpg",
                help_text="Choose a Customer Logo",
                upload_to="email_images",
            ),
        ),
    ]
