# Generated by Django 3.0.7 on 2020-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0008_auto_20200713_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="call_to_action_button_link",
            field=models.CharField(default="http://www.fidelis-partners.com/", max_length=256),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="call_to_action_button_text",
            field=models.CharField(default="Learn More", max_length=256),
        ),
    ]
