# Generated by Django 3.0.7 on 2020-07-21 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_tool", "0010_auto_20200719_0317"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="interest_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONE", "1"),
                    ("TWO", "2"),
                    ("THREE", "3"),
                    ("FOUR", "4"),
                    ("FIVE", "5"),
                ],
                default="ONE",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARTNER", "Partner"),
                    ("OTHER", "Other"),
                    ("NOT_SET", "Not Set"),
                ],
                default="NOT_SET",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="secondary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
