# Generated by Django 3.0.7 on 2020-07-22 04:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0011_auto_20200721_0345"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBatch",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch_title", models.CharField(max_length=50)),
                (
                    "template_file",
                    models.CharField(
                        choices=[("test.html", "TEST")],
                        default="test.html",
                        max_length=256,
                    ),
                ),
                ("subject", models.CharField(max_length=50, null=True)),
                ("title", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "customer_quote",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "custom_message",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("call_to_action_button_text", models.CharField(max_length=256)),
                ("call_to_action_button_link", models.CharField(max_length=256)),
                ("emails_initiated", models.IntegerField()),
                ("emails_skipped", models.IntegerField()),
                (
                    "company_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="company_logo_batches",
                        to="email_tool.ImageResource",
                    ),
                ),
                (
                    "customer_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="customer_image_batches",
                        to="email_tool.ImageResource",
                    ),
                ),
                (
                    "customer_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="custom_logo_batches",
                        to="email_tool.ImageResource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="email_messages",
                to="email_tool.EmailBatch",
            ),
        ),
    ]
