# Generated by Django 3.0.7 on 2020-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0012_auto_20200722_0403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="emails_initiated",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="emails_skipped",
            field=models.IntegerField(default=0),
        ),
    ]
