# Generated by Django 3.0.7 on 2021-01-15 19:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_tool", "0014_auto_20201022_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="next_action_item",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="service_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "IT"),
                    ("STEEL_VIKING", "Steel Viking"),
                    ("NOT_SET", "Not set"),
                    ("OTHER", "Other"),
                ],
                default="NOT_SET",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("PROSPECT", "Prospect"),
                    ("PARTNER", "Partner"),
                    ("OTHER", "Other"),
                    ("NOT_SET", "Not Set"),
                ],
                default="NOT_SET",
                max_length=256,
                null=True,
            ),
        ),
    ]
