# Generated by Django 3.0.7 on 2021-01-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0016_auto_20210118_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="master_company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
