# Generated by Django 3.0.7 on 2021-01-22 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0017_customer_master_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="This is for general descriptions, notes, or any info you want to add about the contact.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="interest_level",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "ONE",
                        "1 – No interest, initial prospect, some interest in the past but has cooled",
                    ),
                    (
                        "TWO",
                        "2 – Promising and ongoing interaction with prospect, meetings happening, possible work identified",
                    ),
                    (
                        "THREE",
                        "3 – Work identified and statement made that prospect wants to ultimately work with us – path forward",
                    ),
                    (
                        "FOUR",
                        "4 – Real opportunity for work under consideration, specific work and timeframe identified, Fidelis identified as serious contender",
                    ),
                    ("FIVE", "5 – Nearing work approval"),
                ],
                default="ONE",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="next_action_item",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="This is for solid, defined next actions. Use the Description field for general notes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="service_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IT", "IT"),
                    ("STEEL_VIKING", "Steel Viking"),
                    ("IT_AND_STEEL_VIKING", "It and Steel Viking"),
                    ("NOT_SET", "Not set"),
                    ("OTHER", "Other"),
                ],
                default="IT",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="This the Target Date for the Next Action Item. This should only be used if there is a Next Action Item.",
                null=True,
            ),
        ),
    ]
