# Generated by Django 3.0.7 on 2021-02-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0018_auto_20210122_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_contacted",
            field=models.DateField(
                blank=True,
                help_text="This is the last time the Customer was contacted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This is for general descriptions, notes, or any info you want to add about the contact.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="next_action_item",
            field=models.TextField(
                blank=True,
                help_text="This is for solid, defined next actions. Use the Description field for general notes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="This is the Target Date for the Next Action Item. This should only be used if there is a Next Action Item.",
                null=True,
            ),
        ),
    ]
