# Generated by Django 3.0.7 on 2021-02-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_tool", "0021_auto_20210213_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="The person assigned to complete the Next Action Item.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assignee",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_contacted",
            field=models.DateField(
                blank=True,
                help_text="This is the last time the Customer was contacted.",
                null=True,
                verbose_name="Last contacted",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="master_company",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Master company"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The Customer's primary contact at Fidelis.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Primary contact",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="This is the Target Date for the Next Action Item. This should only be used if there is a Next Action Item.",
                null=True,
                verbose_name="Target date",
            ),
        ),
    ]
