# Generated by Django 3.0.7 on 2021-02-16 21:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0022_auto_20210216_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="call_to_action_button_link",
            field=models.CharField(
                help_text="This will be the link that a user is sent to after clicking the main Call To Action button in the email.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="call_to_action_button_text",
            field=models.CharField(
                help_text="This will be the text used for the main Call To Action button in the email. You want to make it something short and attention-grabbing.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="company_logo",
            field=models.ForeignKey(
                help_text="Our company logo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_logo_batches",
                to="email_tool.ImageResource",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="custom_message",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="customer_image",
            field=models.ForeignKey(
                help_text="This will be deprecated but WILL be used in the email right now as the 'main' image right below the Title.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="customer_image_batches",
                to="email_tool.ImageResource",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="customer_logo",
            field=models.ForeignKey(
                help_text="This will be deprecated and will not be used in the email currently but you still need to chose one for now.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="custom_logo_batches",
                to="email_tool.ImageResource",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="customer_quote",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="emails_initiated",
            field=models.IntegerField(
                default=0,
                help_text="The number of emails that were sent in this batch.",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="emails_skipped",
            field=models.IntegerField(
                default=0,
                help_text="The number of emails skipped in this batch due to Customers that have unsubscribed.",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="title",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
