# Generated by Django 3.0.7 on 2021-02-26 03:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0023_auto_20210216_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=50, null=True
            ),
        ),
    ]
