# Generated by Django 3.0.7 on 2021-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0024_auto_20210225_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="template_file",
            field=models.CharField(
                choices=[("simple.html", "SIMPLE"), ("modern_standard.html", "MODERN_STANDARD")],
                default="modern_standard.html",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="template_file",
            field=models.CharField(
                choices=[("simple.html", "SIMPLE"), ("modern_standard.html", "MODERN_STANDARD")],
                default="modern_standard.html",
                max_length=256,
            ),
        ),
    ]
