# Generated by Django 3.0.7 on 2021-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0025_auto_20210227_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="subject",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="subject",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
