# Generated by Django 3.0.7 on 2021-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0026_auto_20210305_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
