# Generated by Django 3.0.7 on 2021-03-24 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_tool", "0028_emailbatch_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="NextActionItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(help_text="Describe this Next Action Item.", max_length=256)),
                (
                    "target_date",
                    models.DateField(
                        help_text="The Target Date for this Next Action Item.", verbose_name="Target date"
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="IMPORTANT: Add the completed time once this Next Action Item is completed.",
                        null=True,
                        verbose_name="Completed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person assigned to complete this Next Action Item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignee",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The Customer this Next Action Item relates to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_tool.Customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next Action Item",
                "verbose_name_plural": "Next Action Items",
            },
        ),
    ]
