# Generated by Django 3.0.7 on 2021-03-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0030_next_action_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="alt_company_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="If one is not chosen, the above Company Logo will be used.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="email_tool.ImageResource",
                verbose_name="Secondary company logo",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="alt_company_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="If one is not chosen, the above Company Logo will be used.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="email_tool.ImageResource",
                verbose_name="Secondary Company logo",
            ),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="company_logo",
            field=models.ForeignKey(
                help_text="Primary company logo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_logo_batches",
                to="email_tool.ImageResource",
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="company_logo",
            field=models.ForeignKey(
                help_text="Primary Company logo",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_logo_emails",
                to="email_tool.ImageResource",
            ),
        ),
    ]
