# Generated by Django 3.0.7 on 2021-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0031_auto_20210328_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageresource",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this Image will be archived and hidden from the default list view.",
            ),
        ),
    ]
