# Generated by Django 3.0.7 on 2021-03-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0032_imageresource_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageresource",
            name="category",
            field=models.CharField(
                choices=[("Internal", "Internal"), ("Customer", "Customer"), ("Marketing", "Marketing")],
                default="Marketing",
                max_length=16,
            ),
        ),
    ]
