# Generated by Django 3.0.7 on 2021-03-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0033_imageresource_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailbatch",
            name="customer_logo",
        ),
        migrations.RemoveField(
            model_name="emailmessage",
            name="customer_logo",
        ),
    ]
