# Generated by Django 3.0.7 on 2021-03-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0034_remove_customer_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailbatch",
            old_name="customer_image",
            new_name="primary_image",
        ),
        migrations.RenameField(
            model_name="emailmessage",
            old_name="customer_image",
            new_name="primary_image",
        ),
    ]
