# Generated by Django 3.0.7 on 2021-03-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("email_tool", "0035_change_customer_image_column_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="primary_image",
            field=models.ForeignKey(
                help_text="The primary marketing image for the email.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="primary_image_batches",
                to="email_tool.ImageResource",
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="primary_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary marketing image for the email.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="primary_image_emails",
                to="email_tool.ImageResource",
            ),
        ),
    ]
